export const theme = {
    font1: 'Josefin Sans',
    font2: 'Cormorant Infant',
    fontSide: '15px',
    wrapperXs: '921px',
    wrapper: '1100px',
    wrapperXl: '1440px,',
    colors: {
        transparent: 'transparent',
        grey: '#40464F',
        white: '#FFFFFF',
        yellow: '#E1B168',
        lightgrey: '#797E89',
        black: '#292E36',
        salmon: '#FA8072',
    },
    gap: {
        xxs: '4px',
        xs: '8px',
        sm: '16px',
        md: '32px',
        lg: '64px',
        xl: '72px',
        xxl: '128px',
    },
}; 